<template>
  <div>
    <Breadcrumb title="Create Delivery Notes" :routes="routes" />
    <hr class="-mx-[24px] mb-[24px]" />

    <div class="border border-gray-200 rounded-xl p-[24px]">
      <!-- Header Section -->
      <div class="mb-[24px]">
        <h3 class="text-lg font-semibold">Delivery Notes Information</h3>
      </div>

      <!-- Form Card -->
      <div class="border border-gray-200 rounded-xl p-[24px] mb-[24px]">
        <h3 class="text-lg font-semibold mb-4">Delivery Details</h3>
        <div class="grid grid-cols-1 lg:grid-cols-12 gap-6">
          <!-- Left and Middle Columns - Form Fields (8 columns) -->
          <div class="lg:col-span-8">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-3">
              <!-- Left Column -->
              <div class="space-y-3">
                <!-- PO Number with Search -->
                <div class="flex items-center gap-4">
                  <label class="form-label text-sm font-medium text-gray-600 w-40 mb-0"
                    >PO Number <span class="text-red-500">*</span></label
                  >
                  <div class="flex-1 relative">
                    <div class="flex gap-2">
                      <input
                        v-model="poNumberSearch"
                        type="text"
                        class="input flex-1"
                        placeholder="Enter PO Number"
                        data-focus-key="po-search"
                        @keypress.enter="searchPO"
                      />
                      <button class="btn btn-primary" @click="searchPO" :disabled="isSearching">
                        <i class="ki-duotone ki-search" v-if="!isSearching"></i>
                        <span v-if="isSearching">Loading...</span>
                        <span v-else>Search</span>
                      </button>
                    </div>
                  </div>
                </div>

                <!-- Selected PO Info -->
                <div v-if="selectedPO" class="bg-blue-50 p-3 rounded-lg text-sm">
                  <div class="font-medium text-blue-700">
                    Selected: {{ selectedPO.poNumber }} - {{ selectedPO.vendorName }}
                  </div>
                </div>

                <!-- Delivery Note Number (Auto-generated by backend if left empty) -->
                <!-- READ ONLY -->
                <!-- <div class="flex items-center gap-4">
                  <label class="form-label text-sm font-medium text-gray-600 w-40 mb-0"
                    >Delivery Note #</label
                  >
                  <div class="flex-1">
                    <input
                      v-model="formData.deliveryNoteNumber"
                      type="text"
                      class="input w-full"
                      placeholder="Leave empty to auto-generate (e.g. DN/PO123-001)"
                    />
                    <p class="text-xs text-gray-400 mt-1">
                      Auto-generated as <span class="font-mono">DN/[PO Number]-[seq]</span> if left empty
                    </p>
                  </div>
                </div> -->

                <!-- Vendor Code -->
                <div class="flex items-center gap-4">
                  <label class="form-label text-sm font-medium text-gray-600 w-40 mb-0"
                    >Vendor Code <span class="text-red-500">*</span></label
                  >
                  <input
                    v-model="formData.vendorCode"
                    type="text"
                    class="input flex-1"
                    placeholder="Enter Vendor Code"
                    data-focus-key="vendor-code"
                  />
                </div>

                <!-- Vendor Name (Read-only from PO) -->
                <div class="flex items-center gap-4">
                  <label class="form-label text-sm font-medium text-gray-600 w-40 mb-0"
                    >Vendor Name</label
                  >
                  <input
                    v-model="formData.vendorName"
                    type="text"
                    class="input flex-1 bg-gray-100"
                    placeholder="Auto-filled from PO"
                    readonly
                  />
                </div>

                <!-- Trip ID -->
                <div class="flex items-center gap-4">
                  <label class="form-label text-sm font-medium text-gray-600 w-40 mb-0"
                    >Trip ID</label
                  >
                  <input
                    v-model="formData.tripID"
                    type="text"
                    class="input flex-1"
                    placeholder="Enter Trip ID"
                  />
                </div>

                <!-- Driver Name -->
                <div class="flex items-center gap-4">
                  <label class="form-label text-sm font-medium text-gray-600 w-40 mb-0"
                    >Driver Name <span class="text-red-500">*</span></label
                  >
                  <input
                    v-model="formData.driverName"
                    type="text"
                    class="input flex-1"
                    placeholder="Enter Driver Name"
                    data-focus-key="driver-name"
                  />
                </div>

                <!-- License Plate -->
                <div class="flex items-center gap-4">
                  <label class="form-label text-sm font-medium text-gray-600 w-40 mb-0"
                    >License Plate <span class="text-red-500">*</span></label
                  >
                  <input
                    v-model="formData.licensePlate"
                    type="text"
                    class="input flex-1"
                    placeholder="Enter License Plate"
                    data-focus-key="license-plate"
                  />
                </div>

                <!-- Transporter (Creatable Select) -->
                <div class="flex items-center gap-4">
                  <label class="form-label text-sm font-medium text-gray-600 w-40 mb-0"
                    >Transporter <span class="text-red-500">*</span></label
                  >
                  <div class="flex-1 relative" data-focus-key="transporter">
                    <input
                      v-model="formData.transporter"
                      type="text"
                      class="input w-full"
                      placeholder="Type or select transporter"
                      :list="'transporter-options'"
                      @focus="showTransporterList = true"
                      @blur="hideTransporterList"
                    />
                    <ul
                      v-if="showTransporterList && filteredTransporterOptions.length > 0"
                      class="absolute z-50 w-full bg-white border border-gray-200 rounded-lg shadow-lg mt-1 max-h-48 overflow-y-auto"
                    >
                      <li
                        v-for="opt in filteredTransporterOptions"
                        :key="opt"
                        class="px-3 py-2 text-sm cursor-pointer hover:bg-blue-50 hover:text-blue-700"
                        @mousedown.prevent="selectTransporter(opt)"
                      >
                        {{ opt }}
                      </li>
                    </ul>
                  </div>
                </div>
              </div>

              <!-- Right Column -->
              <div class="space-y-3">
                <!-- Pickup Address -->
                <div class="flex items-center gap-4">
                  <label class="form-label text-sm font-medium text-gray-600 w-36 mb-0"
                    >Pickup Address <span class="text-red-500">*</span></label
                  >
                  <input
                    v-model="formData.pickupAddress"
                    type="text"
                    class="input flex-1"
                    placeholder="Enter Pickup Address"
                    data-focus-key="pickup-address"
                  />
                </div>

                <!-- Destination Address -->
                <div class="flex items-center gap-4">
                  <label class="form-label text-sm font-medium text-gray-600 w-36 mb-0"
                    >Destination <span class="text-red-500">*</span></label
                  >
                  <input
                    v-model="formData.destinationAddress"
                    type="text"
                    class="input flex-1"
                    placeholder="Enter Destination Address"
                    data-focus-key="destination-address"
                  />
                </div>

                <!-- Truck Type (Creatable Select) -->
                <div class="flex items-center gap-4">
                  <label class="form-label text-sm font-medium text-gray-600 w-36 mb-0"
                    >Truck Type</label
                  >
                  <div class="flex-1 relative">
                    <input
                      v-model="formData.truckType"
                      type="text"
                      class="input w-full"
                      placeholder="Type or select truck type"
                      @focus="showTruckTypeList = true"
                      @blur="hideTruckTypeList"
                    />
                    <ul
                      v-if="showTruckTypeList && filteredTruckTypeOptions.length > 0"
                      class="absolute z-50 w-full bg-white border border-gray-200 rounded-lg shadow-lg mt-1 max-h-48 overflow-y-auto"
                    >
                      <li
                        v-for="opt in filteredTruckTypeOptions"
                        :key="opt"
                        class="px-3 py-2 text-sm cursor-pointer hover:bg-blue-50 hover:text-blue-700"
                        @mousedown.prevent="selectTruckType(opt)"
                      >
                        {{ opt }}
                      </li>
                    </ul>
                  </div>
                </div>

                <!-- Estimated Arrival -->
                <div class="flex items-center gap-4">
                  <label class="form-label text-sm font-medium text-gray-600 w-36 mb-0"
                    >Estimated Arrival <span class="text-red-500">*</span></label
                  >
                  <input
                    v-model="formData.estimatedArrival"
                    type="datetime-local"
                    class="input flex-1"
                    :min="todayDateTimeMin"
                    data-focus-key="estimated-arrival"
                  />
                </div>

                <!-- Status -->
                <!-- <div class="flex items-center gap-4">
                  <label class="form-label text-sm font-medium text-gray-600 w-36 mb-0"
                    >Status <span class="text-red-500">*</span></label
                  >
                  <select v-model="formData.status" class="form-select flex-1">
                    <option value="Draft">Draft</option>
                    <option value="Waiting Approval">Waiting Approval</option>
                    <option value="Received">Received</option>
                  </select>
                </div> -->
              </div>
            </div>
          </div>

          <!-- Right Column - Signature + Vendor Delivery Doc (4 columns) -->
          <div class="lg:col-span-4 flex flex-col gap-4">
            <!-- Driver Signature -->
            <div>
              <label class="form-label text-sm font-medium text-gray-600"
                >Driver Signature <span class="text-red-500">*</span></label
              >
              <div
                class="border border-gray-300 rounded-lg p-4 mt-2 bg-gray-50"
                data-focus-key="signature"
                tabindex="-1"
              >
                <!-- Signature Pad -->
                <VueSignature
                  ref="signaturePad"
                  :sigOption="signatureOptions"
                  :w="'100%'"
                  :h="'240px'"
                  class="signature-pad"
                />

                <!-- Clear Button -->
                <div class="mt-3">
                  <button class="btn btn-sm btn-danger w-full" @click="clearSignature">
                    <i class="ki-duotone ki-trash"></i>
                    Clear
                  </button>
                </div>

                <!-- Label -->
                <div class="text-center mt-3">
                  <p class="text-sm font-semibold text-gray-700">Driver Signature</p>
                </div>
              </div>
            </div>

            <!-- Vendor Delivery Document Upload -->
            <div>
              <label class="form-label text-sm font-medium text-gray-600">
                Vendor Delivery Document (Vendor)
                <span class="text-xs text-gray-400 font-normal ml-1">(optional, PDF/image)</span>
              </label>
              <div class="mt-2">
                <div
                  v-if="!vendorDocFile"
                  class="border-2 border-dashed border-gray-300 rounded-lg p-4 text-center hover:border-blue-400 transition-colors cursor-pointer"
                  @click="triggerVendorDocUpload"
                  @dragover.prevent
                  @drop.prevent="handleVendorDocDrop"
                >
                  <i class="ki-duotone ki-document-up text-2xl text-gray-400 mb-1"></i>
                  <p class="text-xs text-gray-500">Click to upload or drag & drop</p>
                  <p class="text-xs text-gray-400">PDF, PNG, JPG up to 5MB</p>
                </div>
                <div
                  v-else
                  class="border border-green-200 bg-green-50 rounded-lg p-3 flex flex-col items-center justify-center min-h-[120px]"
                >
                  <div class="w-full h-full p-2 flex flex-col">
                    <iframe
                      v-if="vendorDocBase64.startsWith('data:application/pdf')"
                      :src="vendorDocBase64"
                      class="w-full h-[150px] border border-gray-200 rounded mb-2"
                    ></iframe>
                    <img
                      v-else
                      :src="vendorDocBase64"
                      alt="Vendor Delivery Document"
                      class="max-w-full max-h-[150px] object-contain rounded mx-auto mb-2"
                    />
                    <div class="flex items-center justify-center gap-2">
                      <span class="text-sm text-green-700 truncate max-w-[150px]">{{ vendorDocFile.name }}</span>
                      <button
                        class="btn btn-sm btn-icon btn-primary"
                        @click.prevent="previewFile(vendorDocBase64)"
                        title="Full Screen"
                      >
                        <i class="ki-duotone ki-maximize"></i>
                      </button>
                      <button
                        class="btn btn-sm btn-icon btn-danger"
                        @click.prevent="removeVendorDoc"
                        title="Remove"
                      >
                        <i class="ki-duotone ki-trash"></i>
                      </button>
                    </div>
                  </div>
                </div>
                <input
                  ref="vendorDocInput"
                  type="file"
                  accept=".pdf,.png,.jpg,.jpeg"
                  class="hidden"
                  @change="handleVendorDocChange"
                />
                <p v-if="vendorDocUploadError" class="text-xs text-red-500 mt-1">
                  {{ vendorDocUploadError }}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Table Section -->
      <div class="border border-gray-200 rounded-xl p-[24px] mt-[24px]">
        <!-- Table Header -->
        <div class="mb-4 flex justify-between items-center">
          <div>
            <h3 class="text-lg font-semibold">Items List</h3>
            <p class="text-sm text-gray-500 mt-1">Add items to be included in this delivery note</p>
          </div>
          <button class="btn btn-primary btn-sm" @click="addNewItem">
            <i class="ki-duotone ki-plus"></i>
            Add Item
          </button>
        </div>

        <!-- Table -->
        <div class="overflow-x-auto list__table rounded-lg border border-gray-200">
          <table class="table table-xs align-middle text-gray-700 font-medium text-sm">
            <thead>
              <tr>
                <th class="!border-b-teal-500 !bg-teal-100 !text-teal-500 text-center">No</th>
                <th class="!border-b-teal-500 !bg-teal-100 !text-teal-500 text-center">
                  SKU <span class="text-danger">*</span>
                </th>
                <th class="!border-b-teal-500 !bg-teal-100 !text-teal-500 text-center">
                  Description <span class="text-danger">*</span>
                </th>
                <th class="!border-b-teal-500 !bg-teal-100 !text-teal-500 text-center">
                  UOM <span class="text-danger">*</span>
                </th>
                <th class="!border-b-teal-500 !bg-teal-100 !text-teal-500 text-center">
                  Lot No <span class="text-danger">*</span>
                </th>
                <th class="!border-b-teal-500 !bg-teal-100 !text-teal-500 text-center">
                  Qty Ordered
                </th>
                <th class="!border-b-teal-500 !bg-teal-100 !text-teal-500 text-center">
                  Qty Shipped <span class="text-danger">*</span>
                </th>
                <th class="!border-b-teal-500 !bg-teal-100 !text-teal-500 text-center">Action</th>
              </tr>
            </thead>
            <tbody>
              <tr v-if="tableData.length === 0">
                <td colspan="7" class="text-center py-8">
                  <div class="text-gray-400">
                    <i class="ki-duotone ki-information text-3xl mb-2"></i>
                    <p>No items added. Click "Add Item" to start.</p>
                  </div>
                </td>
              </tr>
              <tr v-for="(item, index) in tableData" :key="index">
                <td class="text-center">{{ index + 1 }}</td>
                <td>
                  <input
                    v-model="item.sku"
                    type="text"
                    class="input input-sm w-32"
                    placeholder="SKU"
                    :data-focus-key="`item-${index}-sku`"
                  />
                </td>
                <td>
                  <input
                    v-model="item.description"
                    type="text"
                    class="input input-sm w-48"
                    placeholder="Description"
                    :data-focus-key="`item-${index}-description`"
                  />
                </td>
                <td>
                  <input
                    v-model="item.uom"
                    type="text"
                    class="input input-sm w-20"
                    placeholder="UOM"
                    :data-focus-key="`item-${index}-uom`"
                  />
                </td>
                <td>
                  <input
                    v-model="item.lotNo"
                    type="text"
                    class="input input-sm w-28"
                    placeholder="Lot No"
                    :data-focus-key="`item-${index}-lot-no`"
                  />
                </td>
                <!-- Qty Ordered (readonly reference) -->
                <td class="text-center text-gray-500 text-sm">
                  {{ item.qtyOrdered > 0 ? item.qtyOrdered : '-' }}
                </td>
                <td>
                  <div class="flex flex-col gap-1">
                    <input
                      v-model.number="item.qtyShipped"
                      type="number"
                      min="0"
                      :max="item.qtyOrdered > 0 ? item.qtyOrdered : undefined"
                      class="input input-sm w-24 text-center"
                      :class="{
                        'border-red-500 bg-red-50':
                          item.qtyOrdered > 0 && item.qtyShipped > item.qtyOrdered,
                      }"
                      placeholder="Qty"
                      :data-focus-key="`item-${index}-qty-shipped`"
                      @input="validateQtyShippedInput(index)"
                      @blur="clampQtyShipped(index)"
                    />
                    <p
                      v-if="item.qtyOrdered > 0 && item.qtyShipped > item.qtyOrdered"
                      class="text-red-500 text-xs whitespace-nowrap"
                    >
                      Max: {{ item.qtyOrdered }}
                    </p>
                  </div>
                </td>
                <td class="text-center">
                  <button
                    class="btn btn-sm btn-danger btn-icon"
                    @click="removeItem(index)"
                    title="Remove"
                  >
                    <i class="ki-duotone ki-trash"></i>
                  </button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <!-- Action Buttons -->
      <div class="flex justify-between items-center gap-[8px] mt-[24px]">
        <button
          class="btn btn-outline btn-primary"
          :disabled="isSubmitting || !canSaveDraft"
          @click="submitForm(true)"
        >
          Save as Draft
          <i class="ki-duotone ki-bookmark"></i>
        </button>
        <div class="flex items-center justify-end gap-[8px]">
          <button class="btn btn-outline btn-primary" :disabled="isSubmitting" @click="goBack()">
            <i class="ki-filled ki-arrow-left"></i>
            Back
          </button>
          <button
            class="btn btn-primary"
            :disabled="isSubmitting || !canSubmit"
            @click="submitForm(false)"
          >
            Submit
            <i class="ki-duotone ki-paper-plane"></i>
          </button>
        </div>
      </div>
    </div>

    <!-- Notification Modal -->
    <ModalNotification
      :open="showNotificationModal"
      :id="'notification-modal'"
      :type="notificationModal.type"
      :title="notificationModal.title"
      :text="notificationModal.text"
      :onClose="
        () => {
          showNotificationModal = false
        }
      "
    />
  </div>
</template>

<script lang="ts" setup>
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'
import { type routeTypes } from '@/core/type/components/breadcrumb'
import Breadcrumb from '@/components/BreadcrumbView.vue'
import VueSignature from 'vue3-signature'
import ModalNotification from '@/components/modal/ModalNotification.vue'
import DeliveryNotesService, {
  type MockSapPoData,
  type DeliveryNoteCreatePayload,
} from '@/services/deliveryNotes.service'
import { getUserIdFromToken } from '@/composables/token'
import {
  getTodayDateString,
  isDateTimeBeforeToday,
  validateQtyShipped,
  isBlank,
  validationFail,
  validationOk,
  focusValidationField,
  type FormValidationResult,
} from '@/utils/formValidators'

const router = useRouter()
const todayDateString = getTodayDateString()
const todayDateTimeMin = `${todayDateString}T00:00`

// Interfaces
interface FormData {
  deliveryNoteNumber: string
  poNumber: string
  vendorCode: string
  vendorID: number | undefined
  vendorName: string
  estimatedArrival: string
  pickupAddress: string
  status: string
  destinationAddress: string
  transporter: string
  truckType: string
  licensePlate: string
  driverName: string
  tripID: string
  driverSignature: string | null
  vendorDeliveryDocumentPath?: string
}

interface TableDataItem {
  sku: string
  description: string
  uom: string
  lotNo: string
  qtyOrdered: number
  qtyShipped: number
}

// Breadcrumb
const routes = ref<routeTypes[]>([
  {
    name: 'Delivery Notes Create',
    to: '/delivery-notes-create',
  },
])

// States
const isSubmitting = ref<boolean>(false)
const isSearching = ref<boolean>(false)
const poNumberSearch = ref<string>('')
const selectedPO = ref<MockSapPoData | null>(null)

interface SignaturePadInstance {
  clear: () => void
  save: () => string
  fromDataURL: (data: string) => void
}

const signaturePad = ref<SignaturePadInstance | null>(null)

// Signature options
const signatureOptions = {
  penColor: '#000000',
  backgroundColor: '#ffffff',
}

// Form Data
const formData = ref<FormData>({
  deliveryNoteNumber: '',
  poNumber: '',
  vendorCode: '',
  vendorID: undefined,
  vendorName: '',
  estimatedArrival: '',
  pickupAddress: '',
  status: 'On Delivery',
  destinationAddress: '',
  transporter: '',
  truckType: '',
  licensePlate: '',
  driverName: '',
  tripID: '',
  driverSignature: null,
})

// ─── Creatable Select: Transporter ───────────────────────────────────────────
const TRANSPORTER_OPTIONS = [
  'JNE',
  'J&T Express',
  'SiCepat',
  'Anteraja',
  'Ninja Xpress',
  'Lion Parcel',
  'TIKI',
  'POS Indonesia',
  'ID Express',
  'Wahana',
  'SAP Express',
  'RPX',
  'DHL Express',
  'FedEx',
  'TNT',
]

const showTransporterList = ref(false)
const filteredTransporterOptions = computed(() => {
  const q = formData.value.transporter.toLowerCase().trim()
  if (!q) return TRANSPORTER_OPTIONS
  return TRANSPORTER_OPTIONS.filter((o) => o.toLowerCase().includes(q))
})
const selectTransporter = (opt: string) => {
  formData.value.transporter = opt
  showTransporterList.value = false
}
const hideTransporterList = () =>
  setTimeout(() => {
    showTransporterList.value = false
  }, 150)

// ─── Creatable Select: Truck Type ─────────────────────────────────────────────
const TRUCK_TYPE_OPTIONS = [
  'Tronton',
  'Fuso',
  'CDD (Colt Diesel Double)',
  'CDE (Colt Diesel Engkel)',
  'Pickup Kecil',
  'Box Kecil',
  'Box Besar',
  'Wingbox',
  'Flatbed',
  'Refrigerated Truck',
  'Tanker',
  'Lowbed',
  'Motor Kurir',
]

const showTruckTypeList = ref(false)
const filteredTruckTypeOptions = computed(() => {
  const q = formData.value.truckType.toLowerCase().trim()
  if (!q) return TRUCK_TYPE_OPTIONS
  return TRUCK_TYPE_OPTIONS.filter((o) => o.toLowerCase().includes(q))
})
const selectTruckType = (opt: string) => {
  formData.value.truckType = opt
  showTruckTypeList.value = false
}
const hideTruckTypeList = () =>
  setTimeout(() => {
    showTruckTypeList.value = false
  }, 150)

// ─── Vendor Delivery Document Upload ──────────────────────────────────────────
const vendorDocFile = ref<File | null>(null)
const vendorDocInput = ref<HTMLInputElement | null>(null)
const vendorDocUploadError = ref<string>('')
const vendorDocBase64 = ref<string>('')

const triggerVendorDocUpload = () => {
  vendorDocInput.value?.click()
}

const handleVendorDocFile = (file: File) => {
  vendorDocUploadError.value = ''
  const maxSize = 5 * 1024 * 1024 // 5MB
  if (file.size > maxSize) {
    vendorDocUploadError.value = 'File size exceeds 5MB limit.'
    return
  }
  const allowed = ['application/pdf', 'image/png', 'image/jpeg', 'image/jpg']
  if (!allowed.includes(file.type)) {
    vendorDocUploadError.value = 'Only PDF, PNG, JPG files are allowed.'
    return
  }
  vendorDocFile.value = file
  // Convert to base64
  const reader = new FileReader()
  reader.onload = (e) => {
    vendorDocBase64.value = (e.target?.result as string) || ''
  }
  reader.readAsDataURL(file)
}

const handleVendorDocChange = (event: Event) => {
  const input = event.target as HTMLInputElement
  if (input.files && input.files[0]) handleVendorDocFile(input.files[0])
}

const handleVendorDocDrop = (event: DragEvent) => {
  const file = event.dataTransfer?.files[0]
  if (file) handleVendorDocFile(file)
}

const removeVendorDoc = () => {
  vendorDocFile.value = null
  vendorDocBase64.value = ''
  vendorDocUploadError.value = ''
  if (vendorDocInput.value) vendorDocInput.value.value = ''
}

// ─── File Preview Helper ──────────────────────────────────────────────────────
const previewFile = (urlOrBase64: string | undefined | null) => {
  if (!urlOrBase64) return
  if (urlOrBase64.startsWith('data:')) {
    const newWindow = window.open()
    if (newWindow) {
      if (urlOrBase64.startsWith('data:application/pdf')) {
        newWindow.document.write(
          `<iframe src="${urlOrBase64}" frameborder="0" style="border:0; top:0px; left:0px; bottom:0px; right:0px; width:100%; height:100%;" allowfullscreen></iframe>`,
        )
      } else {
        newWindow.document.write(`<img src="${urlOrBase64}" style="max-width:100%;" />`)
      }
    }
  } else {
    window.open(urlOrBase64, '_blank')
  }
}

// Table Data
const tableData = ref<TableDataItem[]>([])

// Modal state
const showNotificationModal = ref<boolean>(false)
const notificationModal = ref({
  type: 'info' as 'info' | 'success' | 'error' | 'warning',
  title: '',
  text: '',
})

// Methods
const searchPO = async () => {
  if (!poNumberSearch.value.trim()) {
    notificationModal.value = {
      type: 'warning',
      title: 'Validation Error',
      text: 'Please enter a PO Number',
    }
    showNotificationModal.value = true

    return
  }

  isSearching.value = true

  try {
    const result = await DeliveryNotesService.searchPoFromSap(poNumberSearch.value)

    if (!result) {
      notificationModal.value = {
        type: 'info',
        title: 'Not Found',
        text: 'No PO found in SAP system',
      }
      showNotificationModal.value = true
      return
    }

    // Auto-select the result (single object from detail endpoint)
    selectPO(result)
  } catch (error) {
    console.error('Error searching PO:', error)
    notificationModal.value = {
      type: 'error',
      title: 'Error',
      text: 'Failed to search PO. Please try again.',
    }
    showNotificationModal.value = true
  } finally {
    isSearching.value = false
  }
}

const selectPO = (po: MockSapPoData) => {
  selectedPO.value = po

  // Auto-fill form data from selected PO
  formData.value.poNumber = po.poNumber
  formData.value.vendorCode = po.vendorCode
  formData.value.tripID = `TR/${po.poNumber}`
  // Use JWT UserId (= VendorId for vendor users) as the authoritative actor ID.
  // Fall back to the PO's vendorID (converted to number) if the JWT claim is unavailable.
  const jwtVendorId = getUserIdFromToken()
  formData.value.vendorID = jwtVendorId ?? (po.vendorID ? Number(po.vendorID) : undefined)

  formData.value.vendorName = po.vendorName || ''

  // Populate table data from PO items
  if (po.items && po.items.length > 0) {
    tableData.value = po.items.map((item) => ({
      sku: item.sku,
      description: item.itemName,
      uom: item.uom,
      lotNo: '', // User needs to fill this
      qtyOrdered: item.qtyOrdered ?? 0,
      qtyShipped: item.qtyOrdered, // Default to ordered qty, user can edit
    }))
  } else {
    tableData.value = []
  }
}

const addNewItem = () => {
  tableData.value.push({
    sku: '',
    description: '',
    uom: '',
    lotNo: '',
    qtyOrdered: 0,
    qtyShipped: 0,
  })
}

const removeItem = (index: number) => {
  tableData.value.splice(index, 1)
}

const goBack = () => {
  router.push({ name: 'deliveryNotesList' })
}

const clearSignature = () => {
  if (signaturePad.value) {
    signaturePad.value.clear()
  }
}

const validateQtyShippedInput = (index: number) => {
  // Visual feedback is handled by the template binding — no extra logic needed here.
  const item = tableData.value[index]
  if (item.qtyShipped < 0) {
    item.qtyShipped = 0
  }
}

const clampQtyShipped = (index: number) => {
  const item = tableData.value[index]
  if (item.qtyOrdered > 0 && item.qtyShipped > item.qtyOrdered) {
    item.qtyShipped = item.qtyOrdered
  }
  if (item.qtyShipped < 0) {
    item.qtyShipped = 0
  }
}

const showValidationError = (text: string) => {
  notificationModal.value = {
    type: 'warning',
    title: 'Validation Error',
    text,
  }
  showNotificationModal.value = true
}

const trimFormTextFields = () => {
  formData.value.vendorCode = formData.value.vendorCode.trim()
  formData.value.driverName = formData.value.driverName.trim()
  formData.value.licensePlate = formData.value.licensePlate.trim()
  formData.value.transporter = formData.value.transporter.trim()
  formData.value.pickupAddress = formData.value.pickupAddress.trim()
  formData.value.destinationAddress = formData.value.destinationAddress.trim()
  formData.value.tripID = formData.value.tripID.trim()

  for (const item of tableData.value) {
    item.sku = item.sku.trim()
    item.description = item.description.trim()
    item.uom = item.uom.trim()
    item.lotNo = item.lotNo.trim()
  }
}

const getValidationResult = (isDraft = false): FormValidationResult => {
  if (isBlank(formData.value.poNumber)) {
    return validationFail('PO Number wajib diisi.', 'po-search')
  }

  if (isBlank(formData.value.vendorCode)) {
    return validationFail('Vendor Code wajib diisi.', 'vendor-code')
  }

  if (!isDraft && isBlank(formData.value.driverName)) {
    return validationFail('Driver Name wajib diisi.', 'driver-name')
  }

  if (!isDraft && isBlank(formData.value.licensePlate)) {
    return validationFail('License Plate wajib diisi.', 'license-plate')
  }

  if (!isDraft && isBlank(formData.value.transporter)) {
    return validationFail('Transporter wajib diisi.', 'transporter')
  }

  if (!isDraft && isBlank(formData.value.pickupAddress)) {
    return validationFail('Pickup Address wajib diisi.', 'pickup-address')
  }

  if (!isDraft && isBlank(formData.value.destinationAddress)) {
    return validationFail('Destination wajib diisi.', 'destination-address')
  }

  if (!isDraft && isBlank(formData.value.estimatedArrival)) {
    return validationFail('Estimated Arrival Date wajib diisi.', 'estimated-arrival')
  }

  if (
    !isDraft &&
    formData.value.estimatedArrival &&
    isDateTimeBeforeToday(formData.value.estimatedArrival)
  ) {
    return validationFail(
      'Estimated Arrival Date tidak boleh sebelum hari ini.',
      'estimated-arrival',
    )
  }

  if (!isDraft && tableData.value.length === 0) {
    return validationFail('Minimal satu item wajib ditambahkan.')
  }

  for (let i = 0; i < tableData.value.length; i++) {
    const item = tableData.value[i]

    if (!isDraft) {
      if (isBlank(item.sku)) {
        return validationFail(`SKU wajib diisi untuk item #${i + 1}.`, `item-${i}-sku`)
      }
      if (isBlank(item.description)) {
        return validationFail(
          `Description wajib diisi untuk item #${i + 1}.`,
          `item-${i}-description`,
        )
      }
      if (isBlank(item.uom)) {
        return validationFail(`UOM wajib diisi untuk item #${i + 1}.`, `item-${i}-uom`)
      }
      if (isBlank(item.lotNo)) {
        return validationFail(`Lot No wajib diisi untuk item #${i + 1}.`, `item-${i}-lot-no`)
      }
    }

    if (!isDraft || item.sku || item.description || item.uom || item.lotNo || item.qtyShipped > 0) {
      const qtyResult = validateQtyShipped(item.qtyShipped, item.qtyOrdered, !isDraft)
      if (!qtyResult.valid && qtyResult.message) {
        return validationFail(`${qtyResult.message} (item #${i + 1})`, `item-${i}-qty-shipped`)
      }
    }
  }

  if (!isDraft && signaturePad.value) {
    const saveResult = signaturePad.value.save()
    if (!saveResult || saveResult.trim().length === 0) {
      return validationFail('Driver Signature wajib diisi.', 'signature')
    }
  }

  return validationOk()
}

const canSaveDraft = computed(() => getValidationResult(true).valid)
const canSubmit = computed(() => getValidationResult(false).valid)

const validateForm = async (isDraft = false): Promise<boolean> => {
  trimFormTextFields()
  const result = getValidationResult(isDraft)
  if (!result.valid) {
    showValidationError(result.message!)
    await focusValidationField(result.focusKey)
    return false
  }
  return true
}

const submitForm = async (isDraft = false) => {
  if (!(await validateForm(isDraft))) return

  isSubmitting.value = true

  try {
    // Save signature data
    let signatureData = ''
    if (signaturePad.value) {
      const saveResult = signaturePad.value.save()
      console.log('Signature save result:', saveResult)
      console.log('Type of save result:', typeof saveResult)

      // vue3-signature returns the Base64 string directly (not an object)
      if (saveResult && saveResult.trim().length > 0) {
        signatureData = saveResult
        console.log('✅ Signature data captured successfully!')
        console.log('Signature data length:', signatureData.length)
        console.log('First 100 chars:', signatureData.substring(0, 100))
      } else {
        console.warn('⚠️ Signature pad is empty - user did not draw anything')
      }
    } else {
      console.error('❌ Signature pad ref is null')
    }

    console.log('Final signature data length:', signatureData?.length || 0)

    // Convert estimatedArrival to shippingDate (YYYY-MM-DD format)
    const shippingDate = formData.value.estimatedArrival
      ? formData.value.estimatedArrival.split('T')[0]
      : new Date().toISOString().split('T')[0]

    // Ensure vendorID always reflects the JWT actor (set during PO selection, refreshed here as safety net)
    // JWT UserId = VendorId for vendor users. Must be sent as a number (int? on the backend).
    const jwtVendorId = getUserIdFromToken()
    const effectiveVendorID: number | undefined = jwtVendorId ?? formData.value.vendorID

    // Prepare payload according to backend structure
    const payload: DeliveryNoteCreatePayload = {
      // Empty string means backend auto-generates the DN number
      deliveryNoteNumber: formData.value.deliveryNoteNumber.trim() || '',
      poNumber: formData.value.poNumber,
      vendorCode: formData.value.vendorCode,
      vendorID: effectiveVendorID,
      vendorName: formData.value.vendorName || selectedPO.value?.vendorName || '',
      tripID: formData.value.tripID || undefined,
      transporter: formData.value.transporter,
      licensePlate: formData.value.licensePlate,
      driverName: formData.value.driverName,
      pickupAddress: formData.value.pickupAddress,
      destinationAddress: formData.value.destinationAddress,
      driverSignature: signatureData || '', // Ensure always included
      truckType: formData.value.truckType || undefined,
      shippingDate: shippingDate,
      status: isDraft ? 'Draft' : 'On Delivery',
      vendorDeliveryDocumentPath: vendorDocBase64.value || undefined,
      details: isDraft
        ? tableData.value.filter(
            (item) => item.sku || item.description || item.uom || item.lotNo || item.qtyShipped > 0,
          )
        : tableData.value,
    }

    console.log('Submitting delivery note:', payload)
    console.log('Signature in payload:', payload.driverSignature ? 'YES' : 'NO (empty)')

    const createdResult = await DeliveryNotesService.create(payload)

    // The service returns result.content which contains the created delivery note data
    const generatedNumber =
      createdResult?.content?.deliveryNoteNumber ||
      createdResult?.deliveryNoteNumber ||
      payload.deliveryNoteNumber ||
      '(auto-generated)'
    notificationModal.value = {
      type: 'success',
      title: 'Success',
      text: isDraft
        ? `Delivery note saved as draft successfully!\nDelivery Note Number: ${generatedNumber}`
        : `Delivery note created successfully!\nDelivery Note Number: ${generatedNumber}`,
    }
    showNotificationModal.value = true

    // Wait before redirect
    await new Promise((resolve) => setTimeout(resolve, 1500))

    router.push({ name: 'deliveryNotesList' })
  } catch (error) {
    console.error('Error submitting form:', error)
    notificationModal.value = {
      type: 'error',
      title: 'Error',
      text: 'Failed to create delivery note. Please try again.',
    }
    showNotificationModal.value = true
  } finally {
    isSubmitting.value = false
  }
}
</script>

<style lang="scss" scoped>
@media print {
  .btn,
  button {
    display: none;
  }
}

.form-control[readonly],
.input[readonly] {
  background-color: #f5f5f5;
  cursor: not-allowed;
}

.signature-pad {
  border: 1px solid #e5e7eb;
  border-radius: 0.5rem;
  background: white;
  width: 100%;
  overflow: visible;

  :deep(canvas) {
    border-radius: 0.5rem;
    width: 100% !important;
    max-width: 100%;
    height: auto !important;
    max-height: 240px;
    object-fit: contain;
  }
}

.list__table {
  th,
  td {
    white-space: nowrap;
  }

  &::-webkit-scrollbar {
    width: 10px;
    height: 10px;
    background: transparent;
  }

  &::-webkit-scrollbar-thumb {
    width: 10px;
    height: 10px;
    border-radius: 15px;
    background-color: #dbdfe9;
  }
}

.input-sm {
  padding: 0.25rem 0.5rem;
  font-size: 0.875rem;
}
</style>
