export interface TaxObjectCode {
  kode: string;
  nama: string;
  pasal: string;
  statuspph: string;
  normanetto: string;
  tarif: string;
  kap: string;
  kjs: string;
  noCertificate: number;
  skbPasal22: number;
  otherCert: number;
  skbPasal23: number;
  skbPHTB: number;
  dtp: number;
  suket: number;
  skbBungaTabungan: number;
}

export const bpuTaxObjectCodes: TaxObjectCode[] = [
  {
    kode: '22-100-07',
    nama: 'Penjualan Hasil Produksi Kepada Distributor di Dalam Negeri oleh Badan Usaha/Industri Tertentu (Industri Semen)',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '0.25',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-100-08',
    nama: 'Penjualan Hasil Produksi Kepada Distributor di Dalam Negeri oleh Badan Usaha/Industri Tertentu (Industri Baja)',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '0.3',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-100-09',
    nama: 'Penjualan Hasil Produksi Kepada Distributor di Dalam Negeri oleh Badan Usaha/Industri Tertentu (Industri Otomotif)',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '0.45',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-100-10',
    nama: 'Penjualan Hasil Produksi Kepada Distributor di Dalam Negeri oleh Badan Usaha/Industri Tertentu (Industri Farmasi)',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '0.3',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-100-11',
    nama: 'Penjualan Hasil Produksi Kepada Distributor di Dalam Negeri oleh Badan Usaha/Industri Tertentu (industri Kertas)',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '0.1',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-100-12',
    nama: 'Penjualan Kendaraan Bermotor di Dalam Negeri oleh ATPM, APM dan Importir Umum Kendaraan Bermotor',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '0.45',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-100-13',
    nama: 'Pembelian oleh Badan Usaha Berupa Komoditas Tambang Batubara, Mineral Logam dan Mineral Bukan Logam dari Badan atau Orang Pribadi Pemegang IUP',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '1.5',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-100-14',
    nama: 'Penjualan Emas Batangan di Dalam Negeri oleh Badan Usaha',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '0.45',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-100-15',
    nama: 'Pembelian Bahan Hasil Kehutanan yang Belum Melalui Proses Industri Manufaktur, untuk Keperluan Industrinya/Ekspornya oleh Badan Usaha Industri/Eksportir',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '0.25',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-100-16',
    nama: 'Pembelian Bahan Hasil Perkebunan yang Belum Melalui Proses Industri Manufaktur, untuk Keperluan Industrinya/Ekspornya Oleh Badan Usaha Industri/Eksportir',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '0.25',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-100-17',
    nama: 'Pembelian Bahan Hasil Pertanian yang Belum Melalui Proses Industri Manufaktur, untuk Keperluan Industrinya/Ekspornya Oleh Badan Usaha Industri/Eksportir',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '0.25',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-100-18',
    nama: 'Pembelian Bahan Hasil Peternakan yang Belum Melalui Proses Industri Manufaktur, untuk Keperluan Industrinya/Ekspornya Oleh Badan Usaha Industri/Eksportir',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '0.25',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-100-19',
    nama: 'Pembelian Bahan Hasil Perikanan yang Belum Melalui Proses Industri Manufaktur, untuk Keperluan Industrinya/Ekspornya Oleh Badan Usaha Industri/Eksportir',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '0.25',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-100-20',
    nama: 'Penjualan BBM oleh Pertamina atau Anak Perusahaan Pertamina Kepada Selain SPBU/Agen/Penyalur (Tidak Final)',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '0.3',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-100-21',
    nama: 'Penjualan BBM oleh Badan Usaha Selain Pertamina atau Anak Perusahaan Pertamina Kepada Selain SPBU/Agen/Penyalur (Tidak Final)',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '0.3',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-100-22',
    nama: 'Penjualan Pelumas oleh Importir/Produsen',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '0.3',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-100-23',
    nama: 'Penjualan  Pulsa dan Kartu Perdana oleh Penyelenggara Distribusi Tingkat Kedua yang Merupakan\nPemungut PPh Pasal 22',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '0.5',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-100-24',
    nama: 'Penjualan BBG oleh Produsen/Importir Kepada Selain SPBU/Agen/Penyalur (Tidak Final)',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '0.3',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-100-25',
    nama: 'Penjualan Emas Batangan di Dalam Negeri oleh Pengusaha Emas Perhiasan dan/atau Emas Batangan',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '0.25',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-100-26',
    nama: 'Penjualan Emas Perhiasan di Dalam Negeri oleh Pengusaha Emas Perhiasan dan/atau Emas Batangan',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '0.25',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-100-27',
    nama: 'Penjualan Perhiasan Selain dari Emas dan/atau Batu Permata dan/atau Batu Lainnya yang Sejenis oleh Pengusaha Emas Perhiasan dan/atau Emas Batangan',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '0.25',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-101-01',
    nama: 'Penghasilan Sehubungan dengan Transaksi Penjualan Barang, Penyerahan Jasa, dan/atau Persewaan serta Penghasilan Lain Sehubungan dengan Penggunaan Harta yang Dilakukan Melalui Pihak Lain dalam Sistem Informasi Pengadaan Pemerintah',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '0.5',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-101-02',
    nama: 'Penghasilan Sehubungan dengan Transaksi Penjualan Barang, Penyerahan Jasa, dan/atau Persewaan serta Penghasilan Lain Sehubungan dengan Penggunaan Harta yang Dilakukan Melalui Pihak Lain dalam Sistem Informasi Pengadaan Pemerintah',
    pasal: 'Pasal 22',
    statuspph: 'Final',
    normanetto: '100',
    tarif: '0.5',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-102-01',
    nama: 'Penghasilan yang Diterima atau Diperoleh Pedagang Dalam Negeri Penjualan Barang, Penyerahan Jasa, dan/atau Persewaan serta Penghasilan Lain Sehubungan dengan Penggunaan Harta yang Dilakukan Melalui Perdagangan Melalui Sistem Elektronik',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '0.5',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-102-02',
    nama: 'Penghasilan yang Diterima atau Diperoleh Pedagang Dalam Negeri Penjualan Barang, Penyerahan Jasa, dan/atau Persewaan serta Penghasilan Lain Sehubungan dengan Penggunaan Harta yang Dilakukan Melalui Perdagangan Melalui Sistem Elektronik',
    pasal: 'Pasal 22',
    statuspph: 'Final',
    normanetto: '100',
    tarif: '0.5',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-401-01',
    nama: 'Penjualan BBM oleh Pertamina atau Anak Perusahaan Pertamina Kepada SPBU (Final)',
    pasal: 'Pasal 22',
    statuspph: 'Final',
    normanetto: '100',
    tarif: '0.25',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-401-02',
    nama: 'Penjualan BBM oleh Badan Usaha Selain Pertamina atau Anak Perusahaan Pertamina Kepada SPBU/Agen/Penyalur  (Final)',
    pasal: 'Pasal 22',
    statuspph: 'Final',
    normanetto: '100',
    tarif: '0.3',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-401-03',
    nama: 'Penjualan BBG oleh produsen/importir Kepada SPBU/Agen/Penyalur (Final)',
    pasal: 'Pasal 22',
    statuspph: 'Final',
    normanetto: '100',
    tarif: '0.3',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-401-04',
    nama: 'Penjualan BBM oleh Pertamina atau Anak Perusahaan Pertamina kepada Agen/Penyalur selain SPBU (Final)',
    pasal: 'Pasal 22',
    statuspph: 'Final',
    normanetto: '100',
    tarif: '0.3',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-403-01',
    nama: 'Penjualan Barang yang Tergolong Sangat Mewah Selain Rumah Beserta Tanahnya, Apartemen, Kondominium dan Sejenisnya',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '5',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-403-02',
    nama: 'Penjualan Barang yang Tergolong Sangat Mewah Untuk Rumah Beserta Tanahnya, Apartemen, Kondominium dan Sejenisnya',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '1',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-404-01',
    nama: 'Ekspor Komoditas Tambang Batubara, Mineral Logam, dan Mineral Bukan Logam yang Dilakukan Oleh Eksportir, Kecuali WP yang Terikat dalam PKP2B dan KK',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '1.5',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-405-01',
    nama: 'Penghasilan Sehubungan dengan Aset Kripto yang dipungut oleh Penyelenggara Perdagangan Melalui Sistem Elektronik yang Merupakan Pedagang Fisik Aset Kripto',
    pasal: 'Pasal 22',
    statuspph: 'Final',
    normanetto: '100',
    tarif: '0.1',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-405-02',
    nama: 'Penghasilan Sehubungan dengan Aset Kripto yang dipungut oleh Penyelenggara Perdagangan Melalui Sistem Elektronik yang Bukan Merupakan Pedagang Fisik Aset Kripto',
    pasal: 'Pasal 22',
    statuspph: 'Final',
    normanetto: '100',
    tarif: '0.2',
    kap: '411122',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-900-01',
    nama: 'Pembayaran atas Pembelian Barang dan/atau Bahan untuk Kegiatan Usahanya oleh BUMN/Badan Usaha Tertentu',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '1.5',
    kap: '411122',
    kjs: '900',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '22-910-01',
    nama: 'Pemungutan oleh Bendaharawan',
    pasal: 'Pasal 22',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '1.5',
    kap: '411122',
    kjs: '910',
    noCertificate: 1,
    skbPasal22: 1,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-100-01',
    nama: 'Hadiah, Penghargaan, Bonus dan Lainnya Selain yang Telah Dipotong PPh Pasal 21 Ayat (1) Huruf E UU PPh',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '15',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-100-02',
    nama: 'Sewa dan Penghasilan Lain Sehubungan Dengan Penggunaan Harta Kecuali Sewa Tanah dan/atau Bangunan yang Telah Dikenai PPh Pasal 4 Ayat (2) UU PPh.',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-101-01',
    nama: 'Dividen',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '15',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-102-01',
    nama: 'Bunga Selain yang Dikenakan PPh Pasal 4 ayat (2)',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '15',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 1,
  },
  {
    kode: '24-103-01',
    nama: 'Royalti',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '15',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-01',
    nama: 'Jasa Teknik',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-02',
    nama: 'Jasa Manajemen',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-03',
    nama: 'Jasa Konsultan',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-04',
    nama: 'Jasa Penilai (Appraisal)',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-05',
    nama: 'Jasa Aktuaris',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-06',
    nama: 'Jasa Akuntansi, Pembukuan, dan Atestasi Laporan Keuangan',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-07',
    nama: 'Jasa Hukum',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-08',
    nama: 'Jasa Arsitektur',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-09',
    nama: 'Jasa Perencanaan Kota dan Arsitektur Landscape',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-10',
    nama: 'Jasa Perancang (Design)',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-11',
    nama: 'Jasa Pengeboran (Drilling) di Bidang Penambangan Minyak dan Gas Bumi (Migas) Kecuali yang Dilakukan oleh Badan Usaha Tetap (BUT)',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-12',
    nama: 'Jasa Penunjang di Bidang Usaha Panas Bumi dan Penambangan Minyak dan Gas Bumi (Migas)',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-13',
    nama: 'Jasa Penambangan dan Jasa Penunjang di Bidang Usaha Panas Bumi dan Penambangan Minyak dan Gas Bumi (Migas)',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-14',
    nama: 'Jasa Penunjang di Bidang Penerbangan dan Bandar Udara',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-15',
    nama: 'Jasa Penebangan Hutan',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-16',
    nama: 'Jasa Pengolahan Limbah',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-17',
    nama: 'Jasa Penyedia Tenaga Kerja dan/atau Tenaga Ahli (Outsourcing Services)',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-18',
    nama: 'Jasa Perantara dan/atau Keagenan',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-19',
    nama: 'Jasa Bidang Perdagangan Surat-Surat Berharga',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-20',
    nama: 'Jasa Kustodian/Penyimpanan/Penitipan',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-21',
    nama: 'Jasa Pengisian Suara (Dubbing) dan/atau Sulih Suara',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-22',
    nama: 'Jasa Mixing Film',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-23',
    nama: 'Jasa Pembuatan Sarana Promosi Film, Iklan, Poster, Foto, dll',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-24',
    nama: 'Jasa Sehubungan Dengan Software Atau Hardware Atau Sistem Komputer',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-25',
    nama: 'Jasa Pembuatan dan/atau Pengelolaan Website',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-26',
    nama: 'Jasa Internet Termasuk Sambungannya',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-27',
    nama: 'Jasa Penyimpanan, Pengolahan dan/atau Penyaluran Data, Informasi, dan/atau Program',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-28',
    nama: 'Jasa Instalasi/Pemasangan Mesin, Peralatan, Listrik, Telepon, Air, dll',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-29',
    nama: 'Jasa Perawatan/Perbaikan/Pemeliharaan Mesin, Peralatan, Listrik, Telepon, Air, dll',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-30',
    nama: 'Jasa Perawatan Kendaraan dan/atau Alat Transportasi Darat, Laut dan Udara',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-31',
    nama: 'Jasa Maklon',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-32',
    nama: 'Jasa Penyelidikan dan Keamanan',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-33',
    nama: 'Jasa Penyelenggara Kegiatan Atau Event Organizer',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-34',
    nama: 'Jasa Penyediaan Tempat dan/atau Waktu Dalam Media Massa, Media Luar Ruang Atau Media Lain Untuk Penyampaian Informasi, dan/atau Jasa Periklanan',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-35',
    nama: 'Jasa Pembasmian Hama',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-36',
    nama: 'Jasa Kebersihan Atau Cleaning Service',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-37',
    nama: 'Jasa Sedot Septic Tank',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-38',
    nama: 'Jasa Pemeliharaan Kolam',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-39',
    nama: 'Jasa Katering Atau Tata Boga',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-40',
    nama: 'Jasa Freight Forwarding',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-41',
    nama: 'Jasa Logistik',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-42',
    nama: 'Jasa Pengurusan Dokumen',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '24-104-43',
    nama: 'Jasa Pengepakan',
    pasal: 'Pasal 23',
    statuspph: 'Tidak Final',
    normanetto: '100',
    tarif: '2',
    kap: '411124',
    kjs: '100',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 1,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '28-402-01',
    nama: 'Sewa Tanah dan/atau Bangunan',
    pasal: 'Pasal 4 Ayat 2',
    statuspph: 'Final',
    normanetto: '100',
    tarif: '10',
    kap: '411128',
    kjs: '403',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  },
  {
    kode: '28-409-01',
    nama: 'Jasa Konstruksi',
    pasal: 'Pasal 4 Ayat 2',
    statuspph: 'Final',
    normanetto: '100',
    tarif: '1.75',
    kap: '411128',
    kjs: '409',
    noCertificate: 1,
    skbPasal22: 0,
    otherCert: 1,
    skbPasal23: 0,
    skbPHTB: 0,
    dtp: 1,
    suket: 0,
    skbBungaTabungan: 0,
  }
];
